# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
#' Create an evidence synthesis source
#'
#' @param sourceMethod            The source method generating the estimates to synthesize. Can be "CohortMethod" or
#'                                "SelfControlledCaseSeries"
#' @param databaseIds             The database  IDs to include. Use `databaseIds = NULL` to include all database IDs.
#' @param likelihoodApproximation The type of likelihood approximation. Can be "adaptive grid" or "normal".
#'
#' @return
#' An object of type `EvidenceSynthesisSource`.
#'
#' @export
createEvidenceSynthesisSource <- function(sourceMethod = "CohortMethod",
                                          databaseIds = NULL,
                                          likelihoodApproximation = "adaptive grid") {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertChoice(sourceMethod, c("CohortMethod", "SelfControlledCaseSeries"), add = errorMessages)
  checkmate::assertChoice(likelihoodApproximation, c("adaptive grid", "normal"), add = errorMessages)
  checkmate::reportAssertions(collection = errorMessages)

  analysis <- list()
  for (name in names(formals(createEvidenceSynthesisSource))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- "EvidenceSynthesisSource"
  return(analysis)
}

#' Create specifications for the EvidenceSynthesisModule
#'
#' @param evidenceSynthesisAnalysisList A list of objects of type "EvidenceSynthesisAnalysis" as generated
#'                                      by either the [createFixedEffectsMetaAnalysis()] or
#'                                      [createBayesianMetaAnalysis()] function.
#'
#' @return
#' An object of type `EvidenceSynthesisModuleSpecifications`.
#'
#' @export
createEvidenceSynthesisModuleSpecifications <- function(evidenceSynthesisAnalysisList) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertList(evidenceSynthesisAnalysisList, min.len = 1, add = errorMessages)
  for (i in 1:length(evidenceSynthesisAnalysisList)) {
    checkmate::assertClass(evidenceSynthesisAnalysisList[[i]], "EvidenceSynthesisAnalysis", add = errorMessages)
  }
  checkmate::reportAssertions(collection = errorMessages)

  specifications <- list(settings = evidenceSynthesisAnalysisList,
                         module = "EvidenceSynthesisModule",
                         version = "0.0.1",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi")
  class(specifications) <- c("EvidenceSynthesisModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}

#' Create a parameter object for the function computeFixedEffectMetaAnalysis
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param alpha  The alpha (expected type I error) used for the confidence intervals. 
#' @param evidenceSynthesisAnalysisId 
#' @param evidenceSynthesisSource 
#'
#' @export
createFixedEffectsMetaAnalysis <- function(alpha = 0.05,
                                           evidenceSynthesisAnalysisId = 1,
                                           evidenceSynthesisSource = NULL) {
  analysis <- list()
  for (name in names(formals(createFixedEffectsMetaAnalysis))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- c("FixedEffectsMetaAnalysis", "EvidenceSynthesisAnalysis")
  return(analysis)
}

#' Create a parameter object for the function computeBayesianMetaAnalysis
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param chainLength  Number of MCMC iterations. 
#' @param burnIn  Number of MCMC iterations to consider as burn in. 
#' @param subSampleFrequency  Subsample frequency for the MCMC. 
#' @param priorSd  A two-dimensional vector with the standard deviation of the prior for mu and tau, respectively. 
#' @param alpha  The alpha (expected type I error) used for the credible intervals. 
#' @param seed  The seed for the random number generator. 
#' @param evidenceSynthesisAnalysisId 
#' @param evidenceSynthesisSource 
#'
#' @export
createBayesianMetaAnalysis <- function(chainLength = 1100000,
                                       burnIn = 1e+05,
                                       subSampleFrequency = 100,
                                       priorSd = c(2, 0.5),
                                       alpha = 0.05,
                                       seed = 1,
                                       evidenceSynthesisAnalysisId = 1,
                                       evidenceSynthesisSource = NULL) {
  analysis <- list()
  for (name in names(formals(createBayesianMetaAnalysis))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- c("BayesianMetaAnalysis", "EvidenceSynthesisAnalysis")
  return(analysis)
}
