# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
# Copyright 2022 Observational Health Data Sciences and Informatics
#
# This file is part of EvidenceSynthesisModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create an evidence synthesis source
#'
#' @param sourceMethod            The source method generating the estimates to synthesize. Can be "CohortMethod" or
#'                                "SelfControlledCaseSeries"
#' @param databaseIds             The database  IDs to include. Use `databaseIds = NULL` to include all database IDs.
#' @param analysisIds             The source method analysis IDs to include. Use `analysisIds = NULL` to include all
#'                                analysis IDs.
#' @param likelihoodApproximation The type of likelihood approximation. Can be "adaptive grid" or "normal".
#'
#' @return
#' An object of type `EvidenceSynthesisSource`.
#'
#' @export
createEvidenceSynthesisSource <- function(sourceMethod = "CohortMethod",
                                          databaseIds = NULL,
                                          analysisIds = NULL,
                                          likelihoodApproximation = "adaptive grid") {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertChoice(sourceMethod, c("CohortMethod", "SelfControlledCaseSeries"), add = errorMessages)
  if (is.character(databaseIds)) {
    checkmate::assertCharacter(databaseIds, null.ok = TRUE, add = errorMessages)
  } else {
    checkmate::assertIntegerish(databaseIds, null.ok = TRUE, add = errorMessages)
  }
  checkmate::assertIntegerish(analysisIds, null.ok = TRUE, add = errorMessages)
  checkmate::assertChoice(likelihoodApproximation, c("adaptive grid", "normal"), add = errorMessages)
  checkmate::reportAssertions(collection = errorMessages)

  analysis <- list()
  for (name in names(formals(createEvidenceSynthesisSource))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- "EvidenceSynthesisSource"
  return(analysis)
}

#' Create specifications for the EvidenceSynthesisModule
#'
#' @param evidenceSynthesisAnalysisList A list of objects of type "EvidenceSynthesisAnalysis" as generated
#'                                      by either the [createFixedEffectsMetaAnalysis()] or
#'                                      [createBayesianMetaAnalysis()] function.
#'
#' @return
#' An object of type `EvidenceSynthesisModuleSpecifications`.
#'
#' @export
createEvidenceSynthesisModuleSpecifications <- function(evidenceSynthesisAnalysisList) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertList(evidenceSynthesisAnalysisList, min.len = 1, add = errorMessages)
  for (i in 1:length(evidenceSynthesisAnalysisList)) {
    checkmate::assertClass(evidenceSynthesisAnalysisList[[i]], "EvidenceSynthesisAnalysis", add = errorMessages)
  }
  checkmate::reportAssertions(collection = errorMessages)
  specifications <- list(settings = evidenceSynthesisAnalysisList,
                         module = "EvidenceSynthesisModule",
                         version = "0.1.0",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi")
  class(specifications) <- c("EvidenceSynthesisModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}

#' Create parameters for a random-effects meta-analysis
#'
#' @details
#' Use DerSimonian-Laird meta-analysis
#'
#' @param alpha  The alpha (expected type I error) used for the confidence intervals.
#' @param evidenceSynthesisAnalysisId
#' @param evidenceSynthesisSource
#' @param controlType
#'
#' @export
createRandomEffectsMetaAnalysis <- function(alpha = 0.05,
                                            evidenceSynthesisAnalysisId = 1,
                                            evidenceSynthesisDescription = "Random-effects",
                                            evidenceSynthesisSource = NULL,
                                            controlType = "outcome") {
  if (evidenceSynthesisSource$likelihoodApproximation != "normal") {
    stop("Random-effects meta-analysis only supports normal approximation of the likelihood.")
  }
  analysis <- list()
  for (name in names(formals(createFixedEffectsMetaAnalysis))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- c("RandomEffectsMetaAnalysis", "EvidenceSynthesisAnalysis")
  return(analysis)
}


#' Create a parameter object for the function computeFixedEffectMetaAnalysis
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param alpha  The alpha (expected type I error) used for the confidence intervals. 
#' @param evidenceSynthesisAnalysisId 
#' @param evidenceSynthesisDescription 
#' @param evidenceSynthesisSource 
#' @param controlType 
#'
#' @export
createFixedEffectsMetaAnalysis <- function(alpha = 0.05,
                                           evidenceSynthesisAnalysisId = 1,
                                           evidenceSynthesisDescription = "Fixed-effects",
                                           evidenceSynthesisSource = NULL,
                                           controlType = "outcome") {
  analysis <- list()
  for (name in names(formals(createFixedEffectsMetaAnalysis))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- c("FixedEffectsMetaAnalysis", "EvidenceSynthesisAnalysis")
  if (evidenceSynthesisSource$likelihoodApproximation != "normal")
                stop("Fixed-effects meta-analysis only supports normal approximation of the likelihood.")
  return(analysis)
}

#' Create a parameter object for the function computeBayesianMetaAnalysis
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param chainLength  Number of MCMC iterations. 
#' @param burnIn  Number of MCMC iterations to consider as burn in. 
#' @param subSampleFrequency  Subsample frequency for the MCMC. 
#' @param priorSd  A two-dimensional vector with the standard deviation of the prior for mu and tau, respectively. 
#' @param alpha  The alpha (expected type I error) used for the credible intervals. 
#' @param seed  The seed for the random number generator. 
#' @param robust  Whether or not to use a t-distribution model (default: FALSE) 
#' @param evidenceSynthesisAnalysisId 
#' @param evidenceSynthesisDescription 
#' @param evidenceSynthesisSource 
#' @param controlType 
#'
#' @export
createBayesianMetaAnalysis <- function(chainLength = 1100000,
                                       burnIn = 1e+05,
                                       subSampleFrequency = 100,
                                       priorSd = c(2, 0.5),
                                       alpha = 0.05,
                                       seed = 1,
                                       robust = FALSE,
                                       evidenceSynthesisAnalysisId = 1,
                                       evidenceSynthesisDescription = "Bayesian random-effects",
                                       evidenceSynthesisSource = NULL,
                                       controlType = "outcome") {
  analysis <- list()
  for (name in names(formals(createBayesianMetaAnalysis))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- c("BayesianMetaAnalysis", "EvidenceSynthesisAnalysis")
  return(analysis)
}
