# Copyright 2022 Observational Health Data Sciences and Informatics
#
# This file is part of EvidenceSynthesisModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code:
OhdsiRTools::updateCopyrightYearFolder()
OhdsiRTools::findNonAsciiStringsInFolder()


# Generate settings function
moduleInfo <- ParallelLogger::loadSettingsFromJson("MetaData.json")
message(sprintf("Using module version '%s' in settings function.", moduleInfo$Version))
library(EvidenceSynthesis)
# source("extras/SettingsFunctionsStub.R")
rCode <- c("# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. ")
rCode <- c(rCode, readLines("extras/SettingsFunctionsStub.R"))
rCode <- gsub("%module%", moduleInfo$Name, rCode)
rCode <- gsub("%version%", moduleInfo$Version, rCode)
rCode <- ParallelLogger::createArgFunction(functionName = 'computeFixedEffectMetaAnalysis',
                                           excludeArgs = c("data"),
                                           newName = "createFixedEffectsMetaAnalysis",
                                           addArgs = list(evidenceSynthesisAnalysisId = 1,
                                                          evidenceSynthesisSource = NULL),
                                           rCode = rCode)
rCode[grep("class\\(analysis\\) <- \"args\"", rCode)] <- "  class(analysis) <- c(\"FixedEffectsMetaAnalysis\", \"EvidenceSynthesisAnalysis\")"
rCode <- ParallelLogger::createArgFunction(functionName = 'computeBayesianMetaAnalysis',
                                           excludeArgs = c("data"),
                                           newName = "createBayesianMetaAnalysis",
                                           addArgs = list(evidenceSynthesisAnalysisId = 1,
                                                          evidenceSynthesisSource = NULL),
                                           rCode = rCode)
rCode[grep("class\\(analysis\\) <- \"args\"", rCode)] <- "  class(analysis) <- c(\"BayesianMetaAnalysis\", \"EvidenceSynthesisAnalysis\")"

writeLines(rCode, "SettingsFunctions.R")


# Generate renv lock file and activate renv:
OhdsiRTools::createRenvLockFile(rootPackage = "EvidenceSynthesis",
                                includeRootPackage = TRUE,
                                mode = "description",
                                additionalRequiredPackages = c("checkmate",
                                                               "testthat",
                                                               "CohortGenerator"))
renv::init()
