# Copyright 2024 Observational Health Data Sciences and Informatics
#
# This file is part of EvidenceSynthesisModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code:
styler::style_dir()
OhdsiRTools::updateCopyrightYearFolder(path = ".", recursive = F)
OhdsiRTools::updateCopyrightYearFolder(path = "./extras", recursive = F)


# Generate settings functions
moduleInfo <- ParallelLogger::loadSettingsFromJson("MetaData.json")
message(sprintf("Using module version '%s' in settings function.", moduleInfo$Version))
library(EvidenceSynthesis)
rCode <- c("# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. ")
rCode <- c(rCode, readLines("extras/SettingsFunctionsStub.R"))
rCode <- gsub("%module%", moduleInfo$Name, rCode)
rCode <- gsub("%version%", moduleInfo$Version, rCode)
rCode <- ParallelLogger::createArgFunction(functionName = 'computeFixedEffectMetaAnalysis',
                                           excludeArgs = c("data"),
                                           newName = "createFixedEffectsMetaAnalysis",
                                           addArgs = list(evidenceSynthesisAnalysisId = 1,
                                                          evidenceSynthesisDescription = "Fixed-effects",
                                                          evidenceSynthesisSource = NULL,
                                                          controlType = "outcome"),
                                           rCode = rCode)
rCode <- c(rCode[1:(length(rCode) - 2)],
           "  if (evidenceSynthesisSource$likelihoodApproximation != \"normal\")
                stop(\"Fixed-effects meta-analysis only supports normal approximation of the likelihood.\")",
           rCode[(length(rCode) - 1):length(rCode)])

rCode[grep("class\\(analysis\\) <- \"args\"", rCode)] <- "  class(analysis) <- c(\"FixedEffectsMetaAnalysis\", \"EvidenceSynthesisAnalysis\")"
rCode <- ParallelLogger::createArgFunction(functionName = 'computeBayesianMetaAnalysis',
                                           excludeArgs = c("data"),
                                           newName = "createBayesianMetaAnalysis",
                                           addArgs = list(evidenceSynthesisAnalysisId = 1,
                                                          evidenceSynthesisDescription = "Bayesian random-effects",
                                                          evidenceSynthesisSource = NULL,
                                                          controlType = "outcome"),
                                           rCode = rCode)
rCode[grep("class\\(analysis\\) <- \"args\"", rCode)] <- "  class(analysis) <- c(\"BayesianMetaAnalysis\", \"EvidenceSynthesisAnalysis\")"
writeLines(rCode, "SettingsFunctions.R")

# Generate renv lock file for default & dev profiles ------------
# updatedPackages and updatedDevPackages are those packages that either
#   1. Cannot be synced between the HADES-wide lock file and the project lock files
#      since they are not in semver format
#   2. Updates to HADES packages
# NOTE: Mandatory Strategus dependencies:
#   CohortGenerator
#   DatabaseConnector
#   keyring
#   ParallelLogger
#   SqlRender
# are explicitly included in Main.R as library calls to allow renv's init()
# function to find them and include them even if they are not used in the
# module code.

# NOTE: using pre-release of Strategus for these functions
# renv::install("OHDSI/Strategus@renv_lock_validation")
updatedPackages <- list(
  list(
    Package = "askpass",
    Version = "1.2.0",
    Source = "Repository",
    Repository = "CRAN"
  ),
  list(
    Package = "EmpiricalCalibration",
    Version = "3.1.2",
    Source = "Repository",
    Repository = "CRAN"
  ),
  list(
    Package = "Matrix",
    Version = "1.6-0",
    Source = "Repository",
    Repository = "CRAN"
  ),
  list(
    Package = "metafor",
    Version = "4.4-0",
    Source = "Repository",
    Repository = "CRAN"
  ),
  list(
    Package = "evaluate",
    Version = "0.22",
    Source = "Repository",
    Repository = "CRAN"
  ),
  list(
    Package = "SqlRender",
    Version = "1.16.1",
    Source = "Repository",
    Repository = "CRAN"
  ),
  "OHDSI/EvidenceSynthesis@v0.5.0",
  "OHDSI/CohortGenerator@v0.8.1"
)
updatedDevPackages <- list(
  "OHDSI/Eunomia@v1.0.2"
)

# Deactivates and cleans the project to remove any/all old references
renv::deactivate(clean = TRUE)

# Initialize the default profile ---------
renv::activate(profile = NULL)
# Use the implicit option so renv crawls the full project.
renv::init(settings = renv::settings$snapshot.type("implicit"))
# Record the explicit package versions mentioned above
renv::record(updatedPackages)
# Force a restore for the default profile
renv::restore(prompt = FALSE)

# Initialize the dev profile ------------
renv::activate(profile = "dev") # Creates a new profile called "dev" for development

# Remove the "tests" directory from the .renvignore
# so the test dependencies are included in the dev lock file
file.copy(".renvignore", ".renvignore-backup", overwrite = TRUE)
ignoreFileContents <- readLines(".renvignore")
ignoreFileContents <- ignoreFileContents[!grepl("/tests/", ignoreFileContents)]
writeLines(ignoreFileContents, ".renvignore")

# Capture the dependencies
renv::init(profile = "dev") # Init the 'dev' profile renv.lock with the explicit DESCRIPTION references

# Record the updated packages
renv::record(c(updatedPackages, updatedDevPackages), lockfile = "renv/profiles/dev/renv.lock")

# Force a restore for the dev profile
renv::restore(prompt = FALSE)

# Restore the original .renvignore
unlink(".renvignore")
file.rename(".renvignore-backup", ".renvignore")

# Re-activate the default profile - the dev profile is only used for unit tests
renv::activate(profile = NULL) # Sets the default profile as the default for the project

# Sync lock files with HADES-wide lock file --------------
hadesWideLockFileName <- normalizePath("hades-wide.lock")
unlink(hadesWideLockFileName)
utils::download.file(
  url = "https://raw.githubusercontent.com/OHDSI/Hades/main/hadesWideReleases/2023Q3/renv.lock",
  destfile = hadesWideLockFileName
)

# Compare HADES-wide lock file to the dev lock file
hwVsProjDevLockFile <- Strategus::compareLockFiles(
  filename1 = hadesWideLockFileName,
  filename2 = "renv/profiles/dev/renv.lock"
)
hwVsProjDevLockFile[!is.na(hwVsProjDevLockFile$lockfile2Version) & hwVsProjDevLockFile$lockfile1Version != hwVsProjDevLockFile$lockfile2Version, ]

# Compare project default lock file to the dev lock file
projDevVsProjLockFile <- Strategus::compareLockFiles(
  filename1 = "renv/profiles/dev/renv.lock",
  filename2 = "renv.lock"
)
projDevVsProjLockFile[!is.na(projDevVsProjLockFile$lockfile2Version) & projDevVsProjLockFile$lockfile1Version != projDevVsProjLockFile$lockfile2Version, ]

# Given a source of truth lock file, update the target
# lock file. Only replace the version in the target
# lock file if the version is newer. Provide a warning
# for those packages that could not be evaluated by
# version
Strategus::syncLockFile(
  sourceOfTruthLockFileName = hadesWideLockFileName,
  targetLockFileName = "renv/profiles/dev/renv.lock"
)

Strategus::syncLockFile(
  sourceOfTruthLockFileName = "renv/profiles/dev/renv.lock",
  targetLockFileName = "renv.lock"
)

# NOTE: Use the compare functions above to verify the files are in sync
# and add any dependencies that could not be synced automatically to the
# updatedPackages and updatedDevPackages respectively.
